name: rebio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mold.svg
    - assets/water.svg
    - assets/gas.svg
    - assets/brown_sugar.svg
    - assets/images/google_logo.png
    - assets/images/ecoenzyme.png
    - assets/user_defined_contribution.svg
    - assets/fruit_peels.svg
    - assets/images/google-icon.svg
    - assets/images/rebiologo.png